//! The world as data: territories, the cell grid they are painted from, and
//! the zoom pyramid over it.
//!
//! This started life inside realm, as that game's board. It is not a game
//! rule — it is a map of the Earth with a country per cell — and a second
//! caller wanted it (`/map`, where everyone online is right now), so
//! it lives here and realm imports it like anybody else. What stayed behind
//! in `lobby/realm/map.rs` is the part that *is* realm: which maps its
//! create dialog offers, and how a generated world is looked up.
//!
//! "testmap" is a hand-built 12-territory continent used by the engine tests;
//! "earth" is real countries from Natural Earth data, generated by
//! `tools/realm-mapgen` into the two committed assets.

use std::collections::{BTreeMap, VecDeque};
use std::sync::{Arc, LazyLock};

pub type TerritoryId = u16;

/// The water marker in grid cells.
pub const WATER: u16 = u16::MAX;

pub struct Territory {
    pub id: TerritoryId,
    pub iso: String,
    pub name: String,
    pub population: u64,
    pub area_km2: u64,
    /// Land-border neighbors (symmetric).
    pub neighbors: Vec<TerritoryId>,
    /// The connected landmasses this territory has cells on. Almost always
    /// one; a country with an overseas part (France, with French Guiana) has
    /// several, which is exactly the case the routing has to be careful with.
    pub landmasses: Vec<u32>,
    /// Neighbours paired with the landmass the shared border is on. Routing
    /// uses this instead of `neighbors`: a border only helps you if you are
    /// standing on the same landmass as the border itself, or France would be
    /// a bridge from Brazil to Spain.
    pub land_links: Vec<(TerritoryId, u32)>,
    /// Grid coordinates of a representative interior point (labels, cursor
    /// jumps).
    pub center: (u16, u16),
    /// Has coastline: at least one of its cells touches water. Landlocked
    /// countries cannot be invaded from the sea, and (depending on the
    /// game's options) cannot launch a sea attack either.
    pub coastal: bool,
    /// Bounding box in base-grid cells, `(x0, y0, x1, y1)` inclusive —
    /// computed once at map build so "show me this country" can pick a zoom
    /// that actually frames it.
    pub bbox: (u16, u16, u16, u16),
    /// Normalized size weight in [0, 1] over this map:
    /// `(ln(pop+1)/ln(pop_max) + ln(area+1)/ln(area_max)) / 2`. Precomputed at
    /// map build so probability math never re-derives map maxima.
    pub weight: f64,
}

/// Row-major cell grid: `WATER` or a territory id per cell.
pub struct TerritoryGrid {
    pub width: u16,
    pub height: u16,
    pub cells: Vec<u16>,
}

impl TerritoryGrid {
    pub fn territory_at(&self, x: u16, y: u16) -> Option<TerritoryId> {
        if x >= self.width || y >= self.height {
            return None;
        }
        let cell = self.cells[y as usize * self.width as usize + x as usize];
        (cell != WATER).then_some(cell)
    }
}

pub struct WorldMap {
    /// Owned rather than `&'static`: a generated world's identity is built at
    /// runtime from its spec, and every consumer only ever reads it.
    pub id: String,
    pub display_name: String,
    pub territories: Vec<Territory>,
    pub grid: TerritoryGrid,
    /// Zoom-out levels: `mips[i]` halves the previous level's resolution
    /// (majority vote, land beats water on ties so small countries stay
    /// visible). Level 0 is `grid` itself; renderers index via `level()`.
    pub mips: Vec<TerritoryGrid>,
}

impl WorldMap {
    pub fn territory(&self, id: TerritoryId) -> Option<&Territory> {
        self.territories.get(id as usize)
    }

    /// The grid for a zoom level: 0 = full detail, each level up halves both
    /// dimensions. Clamped to the deepest available level.
    pub fn level(&self, zoom: u8) -> &TerritoryGrid {
        if zoom == 0 {
            return &self.grid;
        }
        self.mips
            .get((zoom as usize).min(self.mips.len()) - 1)
            .unwrap_or_else(|| self.mips.last().unwrap_or(&self.grid))
    }

    pub fn max_zoom(&self) -> u8 {
        self.mips.len() as u8
    }

    /// Latitude/longitude of a grid point. The grid is equirectangular over
    /// the whole globe, so this is a straight linear mapping.
    pub fn lat_lon(&self, x: u16, y: u16) -> (f64, f64) {
        let w = self.grid.width.max(1) as f64;
        let h = self.grid.height.max(1) as f64;
        let lon = (x as f64 + 0.5) / w * 360.0 - 180.0;
        let lat = 90.0 - (y as f64 + 0.5) / h * 180.0;
        (lat, lon)
    }

    /// Great-circle kilometres between two territories' centers.
    pub fn distance_km(&self, a: TerritoryId, b: TerritoryId) -> f64 {
        let (Some(ta), Some(tb)) = (self.territory(a), self.territory(b)) else {
            return f64::INFINITY;
        };
        let (lat1, lon1) = self.lat_lon(ta.center.0, ta.center.1);
        let (lat2, lon2) = self.lat_lon(tb.center.0, tb.center.1);
        const EARTH_RADIUS_KM: f64 = 6371.0;
        let (p1, p2) = (lat1.to_radians(), lat2.to_radians());
        let dp = (lat2 - lat1).to_radians();
        let dl = (lon2 - lon1).to_radians();
        let a = (dp / 2.0).sin().powi(2) + p1.cos() * p2.cos() * (dl / 2.0).sin().powi(2);
        2.0 * EARTH_RADIUS_KM * a.sqrt().clamp(0.0, 1.0).asin()
    }

    /// Border-hop distance from a set of sources to every land-reachable
    /// territory: sources are 0, their neighbours 1, and so on. Territories
    /// on another landmass are absent from the map (they are reached by sea,
    /// priced in kilometres instead — see `rulesets::RealmRuleset::sea_hop_km`).
    pub fn hop_distances(&self, sources: &[TerritoryId]) -> BTreeMap<TerritoryId, u32> {
        let mut dist: BTreeMap<TerritoryId, u32> = BTreeMap::new();
        let mut queue: VecDeque<TerritoryId> = VecDeque::new();
        for id in sources {
            if self.territory(*id).is_some() && dist.insert(*id, 0).is_none() {
                queue.push_back(*id);
            }
        }
        while let Some(current) = queue.pop_front() {
            let step = dist[&current] + 1;
            let Some(territory) = self.territory(current) else {
                continue;
            };
            for neighbor in &territory.neighbors {
                if !dist.contains_key(neighbor) {
                    dist.insert(*neighbor, step);
                    queue.push_back(*neighbor);
                }
            }
        }
        dist
    }

    /// Kilometres from the nearest of `sources` to `target`.
    pub fn nearest_distance_km(&self, sources: &[TerritoryId], target: TerritoryId) -> f64 {
        sources
            .iter()
            .map(|s| self.distance_km(*s, target))
            .fold(f64::INFINITY, f64::min)
    }
}

/// Downsample levels until the map fits comfortably in a small terminal
/// (width under ~160 half-block pixels).
pub(crate) fn build_mips(base: &TerritoryGrid) -> Vec<TerritoryGrid> {
    let mut mips: Vec<TerritoryGrid> = Vec::new();
    let mut current = base;
    while current.width > 160 && current.height >= 2 {
        let width = current.width / 2;
        let height = current.height / 2;
        let mut cells = vec![WATER; width as usize * height as usize];
        for y in 0..height {
            for x in 0..width {
                let mut counts: [(u16, u8); 4] = [(WATER, 0); 4];
                let mut n = 0usize;
                for (dx, dy) in [(0, 0), (1, 0), (0, 1), (1, 1)] {
                    let sx = x * 2 + dx;
                    let sy = y * 2 + dy;
                    let cell = current.cells[sy as usize * current.width as usize + sx as usize];
                    if let Some(slot) = counts[..n].iter_mut().find(|(c, _)| *c == cell) {
                        slot.1 += 1;
                    } else {
                        counts[n] = (cell, 1);
                        n += 1;
                    }
                }
                // Majority vote; land wins ties against water.
                let mut best = (WATER, 0u8);
                for (cell, count) in &counts[..n] {
                    let beats =
                        *count > best.1 || (*count == best.1 && best.0 == WATER && *cell != WATER);
                    if beats {
                        best = (*cell, *count);
                    }
                }
                cells[y as usize * width as usize + x as usize] = best.0;
            }
        }
        let level = TerritoryGrid {
            width,
            height,
            cells,
        };
        mips.push(level);
        current = mips.last().unwrap();
    }
    mips
}

/// Mark every territory that touches water. One pass over the base grid,
/// wrapping at the antimeridian because the world does; the poles are edges
/// and count as water, which costs nothing (nobody owns the ice).
pub(crate) fn compute_coastal(territories: &mut [Territory], grid: &TerritoryGrid) {
    let mut coastal = vec![false; territories.len()];
    let width = grid.width as i32;
    let height = grid.height as i32;
    for y in 0..height {
        for x in 0..width {
            let cell = grid.cells[(y * width + x) as usize];
            if cell == WATER {
                continue;
            }
            let Some(slot) = coastal.get_mut(cell as usize) else {
                continue;
            };
            if *slot {
                continue;
            }
            // Four-neighbour check, wrapping east-west.
            for (dx, dy) in [(1, 0), (-1, 0), (0, 1), (0, -1)] {
                let nx = (x + dx).rem_euclid(width);
                let ny = y + dy;
                let neighbour = if ny < 0 || ny >= height {
                    WATER
                } else {
                    grid.cells[(ny * width + nx) as usize]
                };
                if neighbour == WATER {
                    *slot = true;
                    break;
                }
            }
        }
    }
    for (territory, is_coastal) in territories.iter_mut().zip(coastal) {
        territory.coastal = is_coastal;
    }
}

/// Fill in every territory's bounding box from one pass over the base grid.
/// Territories with no cells at all (should not happen: the generator
/// force-paints microstates) keep a degenerate box at their center.
pub(crate) fn compute_bboxes(territories: &mut [Territory], grid: &TerritoryGrid) {
    let mut boxes: Vec<Option<(u16, u16, u16, u16)>> = vec![None; territories.len()];
    for y in 0..grid.height {
        let row = y as usize * grid.width as usize;
        for x in 0..grid.width {
            let cell = grid.cells[row + x as usize];
            if cell == WATER {
                continue;
            }
            let Some(slot) = boxes.get_mut(cell as usize) else {
                continue;
            };
            *slot = Some(match *slot {
                None => (x, y, x, y),
                Some((x0, y0, x1, y1)) => (x0.min(x), y0.min(y), x1.max(x), y1.max(y)),
            });
        }
    }
    for (territory, found) in territories.iter_mut().zip(boxes) {
        territory.bbox = found.unwrap_or((
            territory.center.0,
            territory.center.1,
            territory.center.0,
            territory.center.1,
        ));
    }
}

/// Label every land cell with the landmass it belongs to, then hand each
/// territory the landmasses it sits on and the borders it has *on each of
/// them*.
///
/// This is what stops a country with an overseas part from being a bridge
/// between continents. France holds cells in Europe and in South America, so
/// "France borders Brazil" and "France borders Spain" are both true — but
/// they are true on different landmasses, and a march from Brazil that
/// arrives in French Guiana has not arrived in Europe. Pairing every border
/// with its landmass is what lets the router say so.
pub(crate) fn compute_landmasses(territories: &mut [Territory], grid: &TerritoryGrid) {
    let width = grid.width as i32;
    let height = grid.height as i32;
    const UNLABELLED: u32 = u32::MAX;
    let mut label = vec![UNLABELLED; grid.cells.len()];
    let mut next_label = 0u32;
    let mut stack: Vec<usize> = Vec::new();

    for start in 0..grid.cells.len() {
        if grid.cells[start] == WATER || label[start] != UNLABELLED {
            continue;
        }
        let mass = next_label;
        next_label += 1;
        label[start] = mass;
        stack.push(start);
        while let Some(index) = stack.pop() {
            let x = (index as i32) % width;
            let y = (index as i32) / width;
            // Four-neighbour, wrapping east-west because the world does; the
            // poles are the edge of the map and connect nothing.
            for (dx, dy) in [(1, 0), (-1, 0), (0, 1), (0, -1)] {
                let nx = (x + dx).rem_euclid(width);
                let ny = y + dy;
                if ny < 0 || ny >= height {
                    continue;
                }
                let neighbour = (ny * width + nx) as usize;
                if grid.cells[neighbour] == WATER || label[neighbour] != UNLABELLED {
                    continue;
                }
                label[neighbour] = mass;
                stack.push(neighbour);
            }
        }
    }

    let mut masses: Vec<std::collections::BTreeSet<u32>> =
        vec![Default::default(); territories.len()];
    let mut links: Vec<std::collections::BTreeSet<(TerritoryId, u32)>> =
        vec![Default::default(); territories.len()];
    for y in 0..height {
        for x in 0..width {
            let index = (y * width + x) as usize;
            let cell = grid.cells[index];
            if cell == WATER {
                continue;
            }
            let mass = label[index];
            if let Some(set) = masses.get_mut(cell as usize) {
                set.insert(mass);
            }
            // East and south only: every touching pair is seen once, and
            // recorded both ways.
            for (dx, dy) in [(1, 0), (0, 1)] {
                let nx = (x + dx).rem_euclid(width);
                let ny = y + dy;
                if ny >= height {
                    continue;
                }
                let other = grid.cells[(ny * width + nx) as usize];
                if other == WATER || other == cell {
                    continue;
                }
                if let Some(set) = links.get_mut(cell as usize) {
                    set.insert((other, mass));
                }
                if let Some(set) = links.get_mut(other as usize) {
                    set.insert((cell, mass));
                }
            }
        }
    }

    for ((territory, mass), link) in territories.iter_mut().zip(masses).zip(links) {
        let links: Vec<(TerritoryId, u32)> = link.into_iter().collect();
        // Only landmasses this territory has a *border* on are kept. Earth is
        // tens of thousands of islets, and a territory standing alone on one
        // can walk nowhere from it — carrying those would make the router's
        // node set two orders of magnitude bigger for nothing. Anything
        // reached from such a place is reached by sea, which is priced
        // separately and does not need a node here.
        let linked: std::collections::BTreeSet<u32> = links.iter().map(|(_, m)| *m).collect();
        let _ = mass;
        territory.landmasses = linked.into_iter().collect();
        territory.land_links = links;
    }
}

/// Fill in every territory's `weight` from the map's own maxima.
pub(crate) fn compute_weights(territories: &mut [Territory]) {
    let pop_max = territories.iter().map(|t| t.population).max().unwrap_or(1) as f64;
    let area_max = territories.iter().map(|t| t.area_km2).max().unwrap_or(1) as f64;
    let ln_pop_max = (pop_max + 1.0).ln().max(f64::EPSILON);
    let ln_area_max = (area_max + 1.0).ln().max(f64::EPSILON);
    for t in territories.iter_mut() {
        let wp = ((t.population as f64) + 1.0).ln() / ln_pop_max;
        let wa = ((t.area_km2 as f64) + 1.0).ln() / ln_area_max;
        t.weight = ((wp + wa) / 2.0).clamp(0.0, 1.0);
    }
}

/// The fixed maps, by id. Generated worlds are not here: they are built from
/// a spec rather than looked up, which is what `map_handle` is for.
pub fn map_by_id(id: &str) -> Option<Arc<WorldMap>> {
    match id {
        "testmap" => Some(TESTMAP.clone()),
        "earth" => Some(EARTH.clone()),
        _ => None,
    }
}

/// Real Earth: 242 countries from Natural Earth 50m admin-0 data, generated
/// by `tools/realm-mapgen` into the two committed assets. Multi-part
/// countries are one territory whose neighbors union all their parts (so
/// France borders Brazil via French Guiana); island countries have no land
/// neighbors and are jump-only targets.
static EARTH: LazyLock<Arc<WorldMap>> = LazyLock::new(|| Arc::new(build_earth()));

const EARTH_TERRITORIES_JSON: &str =
    include_str!("../../../../assets/realm/earth_territories.json");
const EARTH_GRID_BIN: &[u8] = include_bytes!("../../../../assets/realm/earth_grid.bin");
const GRID_MAGIC: &[u8; 4] = b"RLM1";

fn build_earth() -> WorldMap {
    let raw: Vec<serde_json::Value> =
        serde_json::from_str(EARTH_TERRITORIES_JSON).expect("valid earth territories asset");
    let mut territories: Vec<Territory> = raw
        .iter()
        .map(|t| Territory {
            id: t["id"].as_u64().expect("id") as TerritoryId,
            iso: t["iso"].as_str().expect("iso").to_string(),
            name: t["name"].as_str().expect("name").to_string(),
            population: t["population"].as_u64().expect("population"),
            area_km2: t["area_km2"].as_u64().expect("area"),
            landmasses: Vec::new(),
            land_links: Vec::new(),
            neighbors: t["neighbors"]
                .as_array()
                .expect("neighbors")
                .iter()
                .map(|n| n.as_u64().expect("neighbor id") as TerritoryId)
                .collect(),
            center: {
                let c = t["center"].as_array().expect("center");
                (
                    c[0].as_u64().expect("cx") as u16,
                    c[1].as_u64().expect("cy") as u16,
                )
            },
            coastal: false,
            bbox: (0, 0, 0, 0),
            weight: 0.0,
        })
        .collect();
    compute_weights(&mut territories);

    let grid = decode_grid(EARTH_GRID_BIN).expect("valid earth grid asset");
    compute_bboxes(&mut territories, &grid);
    compute_coastal(&mut territories, &grid);
    compute_landmasses(&mut territories, &grid);
    assert_eq!(
        u16::from_le_bytes([EARTH_GRID_BIN[9], EARTH_GRID_BIN[10]]) as usize,
        territories.len(),
        "grid/territory asset mismatch"
    );
    let mips = build_mips(&grid);
    WorldMap {
        id: "earth".to_string(),
        display_name: "Earth".to_string(),
        territories,
        grid,
        mips,
    }
}

/// Decode the RLM1 binary: `magic | u16 w | u16 h | u8 flags | u16 count`
/// header then `(u16 run, u16 cell)` pairs row-major. Unknown trailing planes
/// (future terrain) are ignored by decoding exactly width*height cells.
fn decode_grid(bin: &[u8]) -> Option<TerritoryGrid> {
    if bin.len() < 11 || &bin[0..4] != GRID_MAGIC {
        return None;
    }
    let width = u16::from_le_bytes([bin[4], bin[5]]);
    let height = u16::from_le_bytes([bin[6], bin[7]]);
    let total = width as usize * height as usize;
    let mut cells = Vec::with_capacity(total);
    let mut i = 11usize;
    while cells.len() < total && i + 3 < bin.len() {
        let run = u16::from_le_bytes([bin[i], bin[i + 1]]) as usize;
        let cell = u16::from_le_bytes([bin[i + 2], bin[i + 3]]);
        for _ in 0..run {
            cells.push(cell);
        }
        i += 4;
    }
    (cells.len() == total).then_some(TerritoryGrid {
        width,
        height,
        cells,
    })
}

/// Hand-built 12-territory continent: a 4x3 block of territories, each a
/// 12x8-cell rectangle, ringed by 2 cells of water (grid 52x28). Adjacency is
/// the 4-neighborhood of the block layout. Populations and areas vary so
/// weight/strength math has real spread in tests.
static TESTMAP: LazyLock<Arc<WorldMap>> = LazyLock::new(|| Arc::new(build_testmap()));

const TEST_COLS: u16 = 4;
const TEST_ROWS: u16 = 3;
const BLOCK_W: u16 = 12;
const BLOCK_H: u16 = 8;
const MARGIN: u16 = 2;

fn build_testmap() -> WorldMap {
    let names: [(&str, &str, u64, u64); 12] = [
        ("AV", "Avonia", 5_000_000, 100_000),
        ("BR", "Brenn", 20_000_000, 350_000),
        ("CA", "Caldera", 80_000_000, 900_000),
        ("DU", "Dunmark", 1_500_000, 40_000),
        ("EL", "Eldwyn", 12_000_000, 220_000),
        ("FE", "Ferrand", 45_000_000, 600_000),
        ("GY", "Gyre", 300_000, 8_000),
        ("HA", "Halvard", 9_000_000, 150_000),
        ("IS", "Isbell", 140_000_000, 1_800_000),
        ("JU", "Jutta", 3_000_000, 70_000),
        ("KO", "Korvane", 28_000_000, 420_000),
        ("LY", "Lyris", 600_000, 15_000),
    ];

    let mut territories: Vec<Territory> = names
        .iter()
        .enumerate()
        .map(|(i, (iso, name, population, area_km2))| {
            let col = (i as u16) % TEST_COLS;
            let row = (i as u16) / TEST_COLS;
            let mut neighbors = Vec::new();
            if col > 0 {
                neighbors.push((i as u16) - 1);
            }
            if col + 1 < TEST_COLS {
                neighbors.push((i as u16) + 1);
            }
            if row > 0 {
                neighbors.push((i as u16) - TEST_COLS);
            }
            if row + 1 < TEST_ROWS {
                neighbors.push((i as u16) + TEST_COLS);
            }
            Territory {
                id: i as TerritoryId,
                iso: iso.to_string(),
                name: name.to_string(),
                population: *population,
                area_km2: *area_km2,
                neighbors,
                landmasses: Vec::new(),
                land_links: Vec::new(),
                center: (
                    MARGIN + col * BLOCK_W + BLOCK_W / 2,
                    MARGIN + row * BLOCK_H + BLOCK_H / 2,
                ),
                coastal: false,
                bbox: (0, 0, 0, 0),
                weight: 0.0,
            }
        })
        .collect();
    compute_weights(&mut territories);

    let width = MARGIN * 2 + TEST_COLS * BLOCK_W;
    let height = MARGIN * 2 + TEST_ROWS * BLOCK_H;
    let mut cells = vec![WATER; width as usize * height as usize];
    for t in &territories {
        let col = t.id % TEST_COLS;
        let row = t.id / TEST_COLS;
        let x0 = MARGIN + col * BLOCK_W;
        let y0 = MARGIN + row * BLOCK_H;
        for y in y0..y0 + BLOCK_H {
            for x in x0..x0 + BLOCK_W {
                cells[y as usize * width as usize + x as usize] = t.id;
            }
        }
    }

    let grid = TerritoryGrid {
        width,
        height,
        cells,
    };
    compute_bboxes(&mut territories, &grid);
    compute_coastal(&mut territories, &grid);
    compute_landmasses(&mut territories, &grid);

    WorldMap {
        id: "testmap".to_string(),
        display_name: "Testlands".to_string(),
        territories,
        mips: Vec::new(), // already fits any terminal
        grid,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn testmap_shape() {
        let map = map_by_id("testmap").unwrap();
        assert_eq!(map.territories.len(), 12);
        // Adjacency is symmetric.
        for t in &map.territories {
            for n in &t.neighbors {
                assert!(map.territory(*n).unwrap().neighbors.contains(&t.id));
            }
        }
        // Weights normalized, biggest territory carries the max weight.
        let max = map
            .territories
            .iter()
            .max_by(|a, b| a.weight.total_cmp(&b.weight))
            .unwrap();
        assert_eq!(max.iso, "IS");
        assert!(
            map.territories
                .iter()
                .all(|t| (0.0..=1.0).contains(&t.weight))
        );
        // Every territory center lands on its own cells.
        for t in &map.territories {
            assert_eq!(map.grid.territory_at(t.center.0, t.center.1), Some(t.id));
        }
        // Corners are water; out of bounds is None.
        assert_eq!(map.grid.territory_at(0, 0), None);
        assert_eq!(map.grid.territory_at(map.grid.width, 0), None);
    }

    #[test]
    fn earth_mips_halve_and_keep_land() {
        let map = map_by_id("earth").unwrap();
        assert!(map.max_zoom() > 0);
        let mut prev_w = map.grid.width;
        let mut prev_h = map.grid.height;
        for level in &map.mips {
            assert_eq!(level.width, prev_w / 2);
            assert_eq!(level.height, prev_h / 2);
            prev_w = level.width;
            prev_h = level.height;
            assert!(level.cells.iter().any(|c| *c != WATER), "land survives");
        }
        // Deepest level fits a small terminal.
        assert!(map.level(map.max_zoom()).width <= 160);
    }

    #[test]
    fn earth_asset_loads_and_is_consistent() {
        let map = map_by_id("earth").unwrap();
        assert_eq!(map.territories.len(), 242);
        assert_eq!(map.grid.width, 4096);
        assert_eq!(map.grid.height, 2048);
        for t in &map.territories {
            assert_eq!(
                t.id as usize,
                map.territories.iter().position(|x| x.id == t.id).unwrap()
            );
            for n in &t.neighbors {
                assert!(map.territory(*n).unwrap().neighbors.contains(&t.id));
            }
            // Centers sit on the territory's own land.
            assert_eq!(map.grid.territory_at(t.center.0, t.center.1), Some(t.id));
            assert!((0.0..=1.0).contains(&t.weight));
        }
        // Known land border sanity: United Kingdom <-> Ireland.
        let uk = map
            .territories
            .iter()
            .find(|t| t.name == "United Kingdom")
            .unwrap();
        let ie = map
            .territories
            .iter()
            .find(|t| t.name == "Ireland")
            .unwrap();
        assert!(uk.neighbors.contains(&ie.id));
    }
}
