use std::collections::{HashMap, HashSet};

use anyhow::Result;
use chrono::NaiveDate;
use tokio_postgres::Client;
use uuid::Uuid;

use super::chips::{ChipMove, Difficulty, UserChips};
use super::door_run::DoorRunResult;

/// UTC calendar-month window over a `puzzle_date` date column.
const MONTH_DATE_FILTER: &str = "date_trunc('month', now() AT TIME ZONE 'UTC')::date";
/// UTC calendar-month window over a timestamptz column.
const MONTH_TS_FILTER: &str = "date_trunc('month', now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'";
/// Rows kept per board. Deep enough that the page can show an around-you
/// tail for almost everyone; RANK ties can push slightly past it.
const BOARD_DEPTH: i64 = 500;

#[derive(Clone)]
pub struct LeaderboardEntry {
    pub username: String,
    pub user_id: Uuid,
    pub count: u32,
}

#[derive(Clone)]
pub struct RankedEntry {
    pub username: String,
    pub user_id: Uuid,
    pub rank: i64,
    pub value: i64,
    /// Optional flavor after the username (the Lateania boards put the
    /// character's class here). Pure decoration: the page drops it before the
    /// rank, name, or value when width runs short.
    pub note: Option<String>,
}

/// Defines a roster enum plus its `ALL` list from one variant list, the same
/// guarantee as `chip_moves!`: a variant cannot exist without an `ALL` entry,
/// so SQL generated by iterating `ALL` can never silently skip a game.
macro_rules! roster {
    ($(#[$doc:meta])* $name:ident: $($variant:ident),+ $(,)?) => {
        $(#[$doc])*
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        pub enum $name {
            $($variant,)+
        }

        impl $name {
            /// Every variant in declaration order, generated from the same
            /// list as the enum itself. Board and page ordering follow it.
            pub const ALL: &'static [Self] = &[$(Self::$variant),+];
        }
    };
}

roster!(
    /// The daily-puzzle roster. Each variant is one `<game>_daily_wins` fact
    /// table. Everything derived from a daily win, the per-game win-count
    /// boards, Arcade Wins points, today's champions, and the per-user daily
    /// completion statuses, is generated by iterating `ALL`, so adding a
    /// daily game here enrolls it in all four surfaces at once. The one thing
    /// the roster cannot enforce: the new game's win-insert statement must
    /// compose `bump_daily_win_total_sql`, or its all-time board stays empty.
    DailyPuzzle: Sudoku, Nonogram, Minesweeper, Solitaire, LeWord, RubiksCube, SlidingPuzzle
);

roster!(
    /// The score-game roster. Each variant has final-score events in
    /// `game_score_events` plus a legacy best-score table; monthly boards
    /// union both, all-time boards read the legacy table of record.
    ScoreGame: Lateris, TwentyFortyEight, Snake, Traffic
);

roster!(
    /// The external roguelike-door roster: games whose runs are ingested
    /// from their host's log files into `door_runs`
    /// (devdocs/PLAN-ROGUELIKE-BOARDS.md). Each variant gets the uniform
    /// board triple: Wins (all-time), Deepest dive, and Top score (monthly +
    /// all-time), all from the per-window union query.
    DoorGame: Dcss, Nethack, Brogue
);

impl DailyPuzzle {
    /// The stable game key used in activity params and status rows.
    pub const fn key(self) -> &'static str {
        match self {
            Self::Sudoku => "sudoku",
            Self::Nonogram => "nonogram",
            Self::Minesweeper => "minesweeper",
            Self::Solitaire => "solitaire",
            Self::LeWord => "le_word",
            Self::RubiksCube => "rubiks_cube",
            Self::SlidingPuzzle => "sliding_puzzle",
        }
    }

    pub const fn title(self) -> &'static str {
        match self {
            Self::Sudoku => "Sudoku",
            Self::Nonogram => "Nonograms",
            Self::Minesweeper => "Minesweeper",
            Self::Solitaire => "Solitaire",
            Self::LeWord => "Le Word",
            Self::RubiksCube => "Rubik's Cube",
            Self::SlidingPuzzle => "Sliding Puzzle",
        }
    }

    /// The per-user daily-win fact table.
    const fn wins_table(self) -> &'static str {
        match self {
            Self::Sudoku => "sudoku_daily_wins",
            Self::Nonogram => "nonogram_daily_wins",
            Self::Minesweeper => "minesweeper_daily_wins",
            Self::Solitaire => "solitaire_daily_wins",
            Self::LeWord => "le_word_daily_wins",
            Self::RubiksCube => "rubiks_cube_daily_wins",
            Self::SlidingPuzzle => "sliding_puzzle_daily_wins",
        }
    }

    /// SQL expression producing this puzzle's Arcade Wins points for one win
    /// row. Every weight comes from [`Difficulty::points`]; a difficulty key
    /// outside the puzzle's real set scores 0, never a silent default.
    fn points_sql(self) -> String {
        match self {
            Self::Sudoku | Self::Nonogram | Self::Minesweeper | Self::SlidingPuzzle => {
                let whens: String = Difficulty::ALL
                    .iter()
                    .map(|d| format!("WHEN '{}' THEN {}", d.key(), d.points()))
                    .collect::<Vec<_>>()
                    .join(" ");
                format!("CASE difficulty_key {whens} ELSE 0 END")
            }
            Self::Solitaire => format!(
                "CASE difficulty_key WHEN 'draw-1' THEN {} WHEN 'draw-3' THEN {} ELSE 0 END",
                Difficulty::Easy.points(),
                Difficulty::Hard.points()
            ),
            Self::LeWord => Difficulty::Easy.points().to_string(),
            Self::RubiksCube => Difficulty::Medium.points().to_string(),
        }
    }

    /// SQL expression for the difficulty column of a daily-status row.
    /// Fixed-tier puzzles have no difficulty column and report `'daily'`.
    const fn status_difficulty_sql(self) -> &'static str {
        match self {
            Self::Sudoku
            | Self::Nonogram
            | Self::Minesweeper
            | Self::Solitaire
            | Self::SlidingPuzzle => "difficulty_key",
            Self::LeWord | Self::RubiksCube => "'daily'",
        }
    }

    pub fn from_key(key: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|game| game.key() == key)
    }
}

impl DoorGame {
    /// The stable game key used in `door_runs.game`, cursor rows, and
    /// reward-template params.
    pub const fn key(self) -> &'static str {
        match self {
            Self::Dcss => "dcss",
            Self::Nethack => "nethack",
            Self::Brogue => "brogue",
        }
    }

    pub const fn title(self) -> &'static str {
        match self {
            Self::Dcss => "DCSS",
            Self::Nethack => "NetHack",
            Self::Brogue => "Brogue",
        }
    }

    pub fn from_key(key: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|game| game.key() == key)
    }
}

impl ScoreGame {
    /// The `game_score_events.game` key.
    pub const fn score_event_key(self) -> &'static str {
        match self {
            Self::Lateris => "tetris",
            Self::TwentyFortyEight => "2048",
            Self::Snake => "snake",
            Self::Traffic => "traffic",
        }
    }

    pub const fn title(self) -> &'static str {
        match self {
            Self::Lateris => "Lateris",
            Self::TwentyFortyEight => "2048",
            Self::Snake => "Snake",
            Self::Traffic => "Traffic",
        }
    }

    /// The per-user best-score table of record.
    const fn legacy_table(self) -> &'static str {
        match self {
            Self::Lateris => "tetris_high_scores",
            Self::TwentyFortyEight => "twenty_forty_eight_high_scores",
            Self::Snake => "snake_high_scores",
            Self::Traffic => "traffic_high_scores",
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct DailyCompletionStatus {
    pub completed_games: HashSet<DailyPuzzle>,
    pub completed_difficulties: HashSet<(DailyPuzzle, String)>,
}

impl DailyCompletionStatus {
    pub fn completed(&self, game: DailyPuzzle) -> bool {
        self.completed_games.contains(&game)
    }

    pub fn completed_difficulty(&self, game: DailyPuzzle, difficulty_key: &str) -> bool {
        self.completed_difficulties
            .contains(&(game, difficulty_key.to_string()))
    }

    fn mark_completed(&mut self, game: DailyPuzzle, difficulty_key: String) {
        self.completed_games.insert(game);
        self.completed_difficulties.insert((game, difficulty_key));
    }
}

/// Both windows of one board. Every board on the leaderboard page shows the
/// same two: the current UTC calendar month and all-time.
#[derive(Clone, Default)]
pub struct BoardWindows {
    pub monthly: Vec<RankedEntry>,
    pub all_time: Vec<RankedEntry>,
}

/// One UTC-month slice of a connected-time checkpoint. A batch can carry more
/// than one month when it checkpoints sessions spanning a month boundary.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct OnlineTimeIncrement {
    pub user_id: Uuid,
    pub month_start: NaiveDate,
    pub milliseconds: i64,
}

/// The uniform board triple of one roguelike door, over `door_runs` (and,
/// for the dive board, the mid-run depth marks in `door_milestones`).
#[derive(Clone, Default)]
pub struct DoorBoards {
    /// All-time count of won runs ([`DoorRunResult::WINS`]). Single window
    /// by design: a monthly wins race would just mirror the score board.
    pub wins: Vec<RankedEntry>,
    /// Deepest absolute dungeon depth. The end-of-run `depth` alone would be
    /// wrong for winners (crawl stamps the *final* place, and a winner ends
    /// at the surface), so this unions in the depth snapshot every tracked
    /// milestone line carries — the rune/orb/branch moments are exactly the
    /// deep points of a run.
    pub depth: BoardWindows,
    /// Best final score.
    pub score: BoardWindows,
}

#[derive(Clone, Default)]
pub struct LeaderboardData {
    pub today_champions: Vec<LeaderboardEntry>,
    pub user_daily_statuses: HashMap<Uuid, DailyCompletionStatus>,
    pub user_chips: HashMap<Uuid, i64>,
    pub monthly_chip_earners: Vec<RankedEntry>,
    pub arcade_champions: Vec<RankedEntry>,
    pub online_time: BoardWindows,
    pub daily_boards: HashMap<DailyPuzzle, BoardWindows>,
    pub score_boards: HashMap<ScoreGame, BoardWindows>,
    pub door_boards: HashMap<DoorGame, DoorBoards>,
    /// Living Lateania characters by level (ties broken by experience), the
    /// character's class carried in `note`. Snapshot of current characters,
    /// not history: a reset character leaves the board.
    pub lateania_adventurers: Vec<RankedEntry>,
    /// Deepest Frontier zone each living Lateania character has walked into.
    pub lateania_frontier: Vec<RankedEntry>,
}

impl LeaderboardData {
    /// `None` only before the first refresh; the fetch inserts every roster
    /// key, empty boards included.
    pub fn daily_board(&self, puzzle: DailyPuzzle) -> Option<&BoardWindows> {
        self.daily_boards.get(&puzzle)
    }

    pub fn score_board(&self, game: ScoreGame) -> Option<&BoardWindows> {
        self.score_boards.get(&game)
    }

    pub fn door_board(&self, game: DoorGame) -> Option<&DoorBoards> {
        self.door_boards.get(&game)
    }
}

pub async fn fetch_leaderboard_data(client: &Client) -> Result<LeaderboardData> {
    let (
        today_champions,
        user_daily_statuses,
        user_chips,
        monthly_chip_earners,
        arcade_champions,
        online_time,
        daily_monthly,
        daily_all_time,
        score_monthly,
        score_all_time,
        lateania_adventurers,
        lateania_frontier,
        door_monthly,
        door_all_time,
    ) = tokio::try_join!(
        fetch_today_champions(client, 10),
        fetch_today_daily_statuses(client),
        UserChips::all_balances(client),
        fetch_monthly_chip_earners(client, BOARD_DEPTH),
        fetch_arcade_champions(client, BOARD_DEPTH),
        fetch_online_time(client, BOARD_DEPTH),
        fetch_daily_win_boards(client, DailyWindow::Monthly),
        fetch_daily_win_boards(client, DailyWindow::AllTime),
        fetch_score_boards(client, ScoreWindow::Monthly),
        fetch_score_boards(client, ScoreWindow::AllTime),
        fetch_lateania_adventurers(client, BOARD_DEPTH),
        fetch_lateania_frontier(client, BOARD_DEPTH),
        fetch_door_boards(client, DoorWindow::Monthly),
        fetch_door_boards(client, DoorWindow::AllTime),
    )?;

    let door_boards = DoorGame::ALL
        .iter()
        .map(|&game| {
            let monthly = door_monthly.get(&game).cloned().unwrap_or_default();
            let all_time = door_all_time.get(&game).cloned().unwrap_or_default();
            (
                game,
                DoorBoards {
                    wins: all_time.wins,
                    depth: BoardWindows {
                        monthly: monthly.depth,
                        all_time: all_time.depth,
                    },
                    score: BoardWindows {
                        monthly: monthly.score,
                        all_time: all_time.score,
                    },
                },
            )
        })
        .collect();

    let daily_boards = DailyPuzzle::ALL
        .iter()
        .map(|&puzzle| {
            (
                puzzle,
                BoardWindows {
                    monthly: daily_monthly.get(&puzzle).cloned().unwrap_or_default(),
                    all_time: daily_all_time.get(&puzzle).cloned().unwrap_or_default(),
                },
            )
        })
        .collect();
    let score_boards = ScoreGame::ALL
        .iter()
        .map(|&game| {
            (
                game,
                BoardWindows {
                    monthly: score_monthly.get(&game).cloned().unwrap_or_default(),
                    all_time: score_all_time.get(&game).cloned().unwrap_or_default(),
                },
            )
        })
        .collect();

    Ok(LeaderboardData {
        today_champions,
        user_daily_statuses,
        user_chips,
        monthly_chip_earners,
        arcade_champions,
        online_time,
        daily_boards,
        score_boards,
        door_boards,
        lateania_adventurers,
        lateania_frontier,
    })
}

/// Adds one process checkpoint of connected time for every user in a single
/// statement. `flush_id` makes retrying the same uncertain statement
/// idempotent: the service never advances to another batch until this one is
/// confirmed.
pub async fn apply_online_time_batch(
    client: &Client,
    flush_id: Uuid,
    increments: &[OnlineTimeIncrement],
) -> Result<u64> {
    if increments.is_empty() {
        return Ok(0);
    }

    let user_ids: Vec<Uuid> = increments.iter().map(|value| value.user_id).collect();
    let month_starts: Vec<NaiveDate> = increments.iter().map(|value| value.month_start).collect();
    let milliseconds: Vec<i64> = increments.iter().map(|value| value.milliseconds).collect();
    Ok(client
        .execute(
            "WITH raw_increments AS (
                SELECT user_id, month_start, milliseconds
                FROM unnest($1::uuid[], $2::date[], $3::bigint[])
                    AS value(user_id, month_start, milliseconds)
                WHERE milliseconds > 0
            ),
            increments AS (
                SELECT raw.user_id,
                       raw.month_start,
                       SUM(raw.milliseconds)::bigint AS milliseconds
                FROM raw_increments raw
                JOIN users u ON u.id = raw.user_id
                GROUP BY raw.user_id, raw.month_start
            ),
            all_time_increments AS (
                SELECT user_id, SUM(milliseconds)::bigint AS milliseconds
                FROM increments
                GROUP BY user_id
            ),
            all_time_upsert AS (
                INSERT INTO user_online_time (user_id, total_milliseconds, last_flush_id)
                SELECT user_id, milliseconds, $4 FROM all_time_increments
                ON CONFLICT (user_id) DO UPDATE SET
                    total_milliseconds = user_online_time.total_milliseconds
                        + CASE
                            WHEN user_online_time.last_flush_id = EXCLUDED.last_flush_id THEN 0
                            ELSE EXCLUDED.total_milliseconds
                          END,
                    last_flush_id = EXCLUDED.last_flush_id
                RETURNING user_id
            )
            INSERT INTO user_online_time_monthly
                (month_start, user_id, total_milliseconds, last_flush_id)
            SELECT month_start, user_id, milliseconds, $4 FROM increments
            ON CONFLICT (month_start, user_id) DO UPDATE SET
                total_milliseconds = user_online_time_monthly.total_milliseconds
                    + CASE
                        WHEN user_online_time_monthly.last_flush_id = EXCLUDED.last_flush_id THEN 0
                        ELSE EXCLUDED.total_milliseconds
                      END,
                last_flush_id = EXCLUDED.last_flush_id",
            &[&user_ids, &month_starts, &milliseconds, &flush_id],
        )
        .await?)
}

#[derive(Clone, Copy)]
enum DoorWindow {
    Monthly,
    AllTime,
}

/// One window's slice of a door's board triple, straight from the query;
/// [`fetch_leaderboard_data`] zips the two windows into [`DoorBoards`]. The
/// wins family is fetched all-time only, so it stays empty here for Monthly.
#[derive(Clone, Default)]
struct DoorWindowBoards {
    wins: Vec<RankedEntry>,
    depth: Vec<RankedEntry>,
    score: Vec<RankedEntry>,
}

/// One query for every door board in the window, all three families ranked
/// `PARTITION BY (family, game)` — the door twin of [`fetch_score_boards`]'s
/// one-query-per-window shape. Wins count [`DoorRunResult::WINS`] results,
/// all-time only. The dive family unions end-of-run depths with the depth
/// snapshot on every tracked milestone line (see [`DoorBoards::depth`] for
/// why runs alone would rank a clean winner at the surface). The milestone
/// arm only reads `absdepth` values that are purely numeric: `raw` stores the
/// log line's fields as uninterpreted strings, and an unguarded cast would
/// let one malformed value error this query and take every board down with
/// it.
async fn fetch_door_boards(
    client: &Client,
    window: DoorWindow,
) -> Result<HashMap<DoorGame, DoorWindowBoards>> {
    let keys: String = DoorGame::ALL
        .iter()
        .map(|game| format!("'{}'", game.key()))
        .collect::<Vec<_>>()
        .join(", ");
    let win_results: String = DoorRunResult::WINS
        .iter()
        .map(|result| format!("'{}'", result.key()))
        .collect::<Vec<_>>()
        .join(", ");
    let (runs_filter, milestones_filter, wins_arm) = match window {
        DoorWindow::Monthly => (
            format!("AND ended_at >= {MONTH_TS_FILTER}"),
            format!("AND occurred_at >= {MONTH_TS_FILTER}"),
            String::new(),
        ),
        DoorWindow::AllTime => (
            String::new(),
            String::new(),
            format!(
                "SELECT 'wins' AS family, game, user_id, COUNT(*)::bigint AS value
                 FROM runs WHERE result IN ({win_results}) GROUP BY game, user_id
                 UNION ALL"
            ),
        ),
    };
    let rows = client
        .query(
            &format!(
                "WITH runs AS (
                    SELECT game, user_id, result, score, depth
                    FROM door_runs
                    WHERE game IN ({keys}) {runs_filter}
                ),
                dives AS (
                    SELECT game, user_id, depth FROM runs WHERE depth IS NOT NULL
                    UNION ALL
                    SELECT game, user_id, (raw->>'absdepth')::int AS depth
                    FROM door_milestones
                    WHERE game IN ({keys})
                      AND raw->>'absdepth' ~ '^[0-9]+$' {milestones_filter}
                ),
                families AS (
                    {wins_arm}
                    SELECT 'depth' AS family, game, user_id, MAX(depth)::bigint AS value
                    FROM dives GROUP BY game, user_id
                    UNION ALL
                    SELECT 'score' AS family, game, user_id, MAX(score)::bigint AS value
                    FROM runs WHERE score IS NOT NULL GROUP BY game, user_id
                ),
                ranked AS (
                    SELECT f.family,
                           f.game,
                           u.username,
                           f.user_id,
                           f.value,
                           RANK() OVER (
                               PARTITION BY f.family, f.game ORDER BY f.value DESC
                           ) AS rank
                    FROM families f
                    JOIN users u ON u.id = f.user_id
                )
                SELECT family, game, username, user_id, value, rank
                FROM ranked
                WHERE rank <= $1
                ORDER BY family ASC, game ASC, rank ASC, username ASC"
            ),
            &[&BOARD_DEPTH],
        )
        .await?;

    let mut boards: HashMap<DoorGame, DoorWindowBoards> = HashMap::new();
    for row in rows {
        let game =
            DoorGame::from_key(row.get("game")).expect("door board row game key from roster");
        let entry = RankedEntry {
            username: row.get("username"),
            user_id: row.get("user_id"),
            rank: row.get("rank"),
            value: row.get("value"),
            note: None,
        };
        let board = boards.entry(game).or_default();
        match row.get::<_, &str>("family") {
            "wins" => board.wins.push(entry),
            "depth" => board.depth.push(entry),
            "score" => board.score.push(entry),
            other => unreachable!("door board family {other} not produced by this query"),
        }
    }
    Ok(boards)
}

/// Lateania's Frontier room layout, mirrored from
/// `late-ssh/src/app/door/lateania/world.rs` (`extend_frontier`): 20 zones of
/// 50 rooms each, room ids 2000..=2999. late-core cannot depend on the game
/// crate, so the numbers are restated here; a Frontier reshape must update
/// both places.
const LATEANIA_FRONTIER_FIRST_ROOM: i32 = 2000;
const LATEANIA_FRONTIER_LAST_ROOM: i32 = 2999;
const LATEANIA_FRONTIER_ZONE_ROOMS: i32 = 50;

/// Living Lateania characters ranked by level, experience as the tiebreak.
/// The character blob is game-owned JSON (`mud_characters.data`); rows
/// without a chosen class are pre-class-select shells and stay off the board.
async fn fetch_lateania_adventurers(client: &Client, limit: i64) -> Result<Vec<RankedEntry>> {
    let rows = client
        .query(
            "WITH chars AS (
                SELECT c.user_id,
                       (c.data->>'level')::bigint AS level,
                       COALESCE((c.data->>'xp')::bigint, 0) AS xp,
                       initcap(c.data->>'class') AS class
                FROM mud_characters c
                WHERE c.data->>'class' IS NOT NULL
                  AND c.data->>'level' IS NOT NULL
            ),
            ranked AS (
                SELECT u.username,
                       ch.user_id,
                       ch.level,
                       ch.class,
                       RANK() OVER (ORDER BY ch.level DESC, ch.xp DESC) AS rank
                FROM chars ch
                JOIN users u ON u.id = ch.user_id
            )
            SELECT username, user_id, class, level AS value, rank
            FROM ranked
            ORDER BY rank ASC, username ASC
            LIMIT $1",
            &[&limit],
        )
        .await?;
    Ok(rows
        .into_iter()
        .map(|row| RankedEntry {
            username: row.get("username"),
            user_id: row.get("user_id"),
            rank: row.get("rank"),
            value: row.get("value"),
            note: row.get::<_, Option<String>>("class"),
        })
        .collect())
}

/// Deepest Frontier zone per living Lateania character, from the visited-room
/// list in the character blob. This unnests each character's visited array,
/// which is the most per-row work in the leaderboard pass; it stays cheap
/// because `mud_characters` holds one row per player who ever rolled a
/// character, a small table by construction, and the pass itself is
/// subscriber-gated on a 5 minute cadence (`app/leaderboard/svc.rs`).
async fn fetch_lateania_frontier(client: &Client, limit: i64) -> Result<Vec<RankedEntry>> {
    let rows = client
        .query(
            &format!(
                "WITH depths AS (
                    SELECT c.user_id,
                           (MAX((room.value)::int) - {first}) / {zone_rooms} + 1 AS zone
                    FROM (
                        SELECT user_id, data->'visited' AS visited
                        FROM mud_characters
                        WHERE jsonb_typeof(data->'visited') = 'array'
                    ) c
                    CROSS JOIN LATERAL jsonb_array_elements_text(c.visited) AS room(value)
                    WHERE (room.value)::int BETWEEN {first} AND {last}
                    GROUP BY c.user_id
                ),
                ranked AS (
                    SELECT u.username,
                           d.user_id,
                           d.zone::bigint AS zone,
                           RANK() OVER (ORDER BY d.zone DESC) AS rank
                    FROM depths d
                    JOIN users u ON u.id = d.user_id
                )
                SELECT username, user_id, zone AS value, rank
                FROM ranked
                ORDER BY rank ASC, username ASC
                LIMIT $1",
                first = LATEANIA_FRONTIER_FIRST_ROOM,
                last = LATEANIA_FRONTIER_LAST_ROOM,
                zone_rooms = LATEANIA_FRONTIER_ZONE_ROOMS,
            ),
            &[&limit],
        )
        .await?;
    Ok(ranked_entries(rows))
}

async fn fetch_monthly_chip_earners(client: &Client, limit: i64) -> Result<Vec<RankedEntry>> {
    let excluded_reasons = ChipMove::excluded_earning_reasons();
    let rows = client
        .query(
            &format!(
                "WITH totals AS (
                    SELECT user_id, SUM(delta)::bigint AS earned
                    FROM chip_ledger
                    WHERE reason <> ALL($2)
                      AND created_at >= {MONTH_TS_FILTER}
                    GROUP BY user_id
                    HAVING SUM(delta) > 0
                ),
                ranked AS (
                    SELECT u.username,
                           t.user_id,
                           t.earned,
                           RANK() OVER (ORDER BY t.earned DESC) AS rank
                    FROM totals t
                    JOIN users u ON u.id = t.user_id
                )
                SELECT username, user_id, earned AS value, rank
                FROM ranked
                ORDER BY rank ASC, username ASC
                LIMIT $1"
            ),
            &[&limit, &excluded_reasons],
        )
        .await?;
    Ok(ranked_entries(rows))
}

async fn fetch_online_time(client: &Client, limit: i64) -> Result<BoardWindows> {
    let rows = client
        .query(
            &format!(
                "WITH totals AS (
                    SELECT 'monthly'::text AS period,
                           user_id,
                           total_milliseconds AS value
                    FROM user_online_time_monthly
                    WHERE month_start = {MONTH_DATE_FILTER}
                      AND total_milliseconds > 0
                    UNION ALL
                    SELECT 'all_time'::text AS period,
                           user_id,
                           total_milliseconds AS value
                    FROM user_online_time
                    WHERE total_milliseconds > 0
                ),
                ranked AS (
                    SELECT totals.period,
                           u.username,
                           totals.user_id,
                           totals.value,
                           RANK() OVER (
                               PARTITION BY totals.period ORDER BY totals.value DESC
                           ) AS rank
                    FROM totals
                    JOIN users u ON u.id = totals.user_id
                )
                SELECT period, username, user_id, value, rank
                FROM ranked
                WHERE rank <= $1
                ORDER BY period ASC, rank ASC, username ASC"
            ),
            &[&limit],
        )
        .await?;

    let mut windows = BoardWindows::default();
    for row in rows {
        let entry = RankedEntry {
            username: row.get("username"),
            user_id: row.get("user_id"),
            rank: row.get("rank"),
            value: row.get("value"),
            note: None,
        };
        match row.get::<_, &str>("period") {
            "monthly" => windows.monthly.push(entry),
            "all_time" => windows.all_time.push(entry),
            other => unreachable!("online time window {other} not produced by this query"),
        }
    }
    Ok(windows)
}

/// Monthly Arcade Wins points. The per-win `SELECT` arms are generated from
/// [`DailyPuzzle::ALL`], each with its own [`DailyPuzzle::points_sql`]
/// expression, so a new daily game cannot be forgotten here.
async fn fetch_arcade_champions(client: &Client, limit: i64) -> Result<Vec<RankedEntry>> {
    let arms: String = DailyPuzzle::ALL
        .iter()
        .map(|puzzle| {
            format!(
                "SELECT user_id, {points} AS points
                 FROM {table}
                 WHERE puzzle_date >= {MONTH_DATE_FILTER}",
                points = puzzle.points_sql(),
                table = puzzle.wins_table(),
            )
        })
        .collect::<Vec<_>>()
        .join("\nUNION ALL\n");
    let rows = client
        .query(
            &format!(
                "WITH scored AS (
                    {arms}
                ),
                totals AS (
                    SELECT user_id, SUM(points)::bigint AS points
                    FROM scored
                    GROUP BY user_id
                    HAVING SUM(points) > 0
                ),
                ranked AS (
                    SELECT u.username,
                           t.user_id,
                           t.points,
                           RANK() OVER (ORDER BY t.points DESC) AS rank
                    FROM totals t
                    JOIN users u ON u.id = t.user_id
                )
                SELECT username, user_id, points AS value, rank
                FROM ranked
                ORDER BY rank ASC, username ASC
                LIMIT $1"
            ),
            &[&limit],
        )
        .await?;
    Ok(ranked_entries(rows))
}

/// The `daily_win_totals` bump arm for a daily game's win-insert statement.
/// Compose it as a data-modifying CTE after a `win` CTE that returns
/// `user_id` and a `fresh_win` boolean that is true only for rows the
/// statement actually inserted (`xmax = 0` on upserts), so same-day replays
/// never double-count. Riding the insert's own statement is what keeps the
/// rollup drift-free and lets the all-time boards read one row per player
/// instead of counting the full win history.
pub fn bump_daily_win_total_sql(puzzle: DailyPuzzle) -> String {
    format!(
        "INSERT INTO daily_win_totals (game, user_id, wins)
         SELECT '{key}', user_id, 1 FROM win WHERE fresh_win
         ON CONFLICT (game, user_id) DO UPDATE SET wins = daily_win_totals.wins + 1",
        key = puzzle.key(),
    )
}

#[derive(Clone, Copy)]
enum DailyWindow {
    Monthly,
    AllTime,
}

/// One query for every per-puzzle win-count board in the window: rows carry
/// the puzzle key and ranks partition by it. Monthly counts win rows inside
/// the month window; all-time reads the `daily_win_totals` rollup that the
/// win inserts maintain (see `bump_daily_win_total_sql`), so the pass stays
/// O(players) as the win tables grow.
async fn fetch_daily_win_boards(
    client: &Client,
    window: DailyWindow,
) -> Result<HashMap<DailyPuzzle, Vec<RankedEntry>>> {
    let totals_cte = match window {
        DailyWindow::Monthly => {
            let arms: String = DailyPuzzle::ALL
                .iter()
                .map(|puzzle| {
                    format!(
                        "SELECT user_id, '{key}' AS game FROM {table} WHERE puzzle_date >= {MONTH_DATE_FILTER}",
                        key = puzzle.key(),
                        table = puzzle.wins_table(),
                    )
                })
                .collect::<Vec<_>>()
                .join("\nUNION ALL\n");
            format!(
                "wins AS (
                    {arms}
                ),
                totals AS (
                    SELECT game, user_id, COUNT(*)::bigint AS wins
                    FROM wins
                    GROUP BY game, user_id
                )"
            )
        }
        // The roster filter keeps `from_key(...).expect(...)` below honest:
        // rows from a variant later removed from the roster are skipped, not
        // crashed on.
        DailyWindow::AllTime => {
            let keys: String = DailyPuzzle::ALL
                .iter()
                .map(|puzzle| format!("'{}'", puzzle.key()))
                .collect::<Vec<_>>()
                .join(", ");
            format!(
                "totals AS (
                    SELECT game, user_id, wins
                    FROM daily_win_totals
                    WHERE game IN ({keys})
                )"
            )
        }
    };
    let rows = client
        .query(
            &format!(
                "WITH {totals_cte},
                ranked AS (
                    SELECT t.game,
                           u.username,
                           t.user_id,
                           t.wins,
                           RANK() OVER (PARTITION BY t.game ORDER BY t.wins DESC) AS rank
                    FROM totals t
                    JOIN users u ON u.id = t.user_id
                )
                SELECT game, username, user_id, wins AS value, rank
                FROM ranked
                WHERE rank <= $1
                ORDER BY game ASC, rank ASC, username ASC"
            ),
            &[&BOARD_DEPTH],
        )
        .await?;

    let mut boards: HashMap<DailyPuzzle, Vec<RankedEntry>> = HashMap::new();
    for row in rows {
        let key: &str = row.get("game");
        let puzzle = DailyPuzzle::from_key(key).expect("board row game key from roster");
        boards.entry(puzzle).or_default().push(RankedEntry {
            username: row.get("username"),
            user_id: row.get("user_id"),
            rank: row.get("rank"),
            value: row.get("value"),
            note: None,
        });
    }
    Ok(boards)
}

#[derive(Clone, Copy)]
enum ScoreWindow {
    Monthly,
    AllTime,
}

/// One query for every score-game board in the window. Monthly unions
/// `game_score_events` with legacy rows touched this month; all-time reads
/// only the legacy best-score tables, the tables of record that predate
/// score events.
async fn fetch_score_boards(
    client: &Client,
    window: ScoreWindow,
) -> Result<HashMap<ScoreGame, Vec<RankedEntry>>> {
    let arms: String = ScoreGame::ALL
        .iter()
        .map(|game| match window {
            ScoreWindow::Monthly => format!(
                "SELECT user_id, score, '{key}' AS game
                 FROM game_score_events
                 WHERE game = '{key}' AND created_at >= {MONTH_TS_FILTER}
                 UNION ALL
                 SELECT user_id, score, '{key}' AS game
                 FROM {table}
                 WHERE updated >= {MONTH_TS_FILTER}",
                key = game.score_event_key(),
                table = game.legacy_table(),
            ),
            ScoreWindow::AllTime => format!(
                "SELECT user_id, score, '{key}' AS game FROM {table}",
                key = game.score_event_key(),
                table = game.legacy_table(),
            ),
        })
        .collect::<Vec<_>>()
        .join("\nUNION ALL\n");
    let rows = client
        .query(
            &format!(
                "WITH scores AS (
                    {arms}
                ),
                best AS (
                    SELECT game, user_id, MAX(score)::bigint AS score
                    FROM scores
                    GROUP BY game, user_id
                ),
                ranked AS (
                    SELECT b.game,
                           u.username,
                           b.user_id,
                           b.score,
                           RANK() OVER (PARTITION BY b.game ORDER BY b.score DESC) AS rank
                    FROM best b
                    JOIN users u ON u.id = b.user_id
                )
                SELECT game, username, user_id, score AS value, rank
                FROM ranked
                WHERE rank <= $1
                ORDER BY game ASC, rank ASC, username ASC"
            ),
            &[&BOARD_DEPTH],
        )
        .await?;

    let mut boards: HashMap<ScoreGame, Vec<RankedEntry>> = HashMap::new();
    for row in rows {
        let key: &str = row.get("game");
        let game = ScoreGame::ALL
            .iter()
            .copied()
            .find(|game| game.score_event_key() == key)
            .expect("board row game key from roster");
        boards.entry(game).or_default().push(RankedEntry {
            username: row.get("username"),
            user_id: row.get("user_id"),
            rank: row.get("rank"),
            value: row.get("value"),
            note: None,
        });
    }
    Ok(boards)
}

/// Maps a ranked query onto `RankedEntry`. Every such query projects exactly
/// `username, user_id, value, rank`, so there is no column left to name and
/// nothing a call site can get wrong. Keep the descriptive name (`wins`,
/// `points`) inside the CTEs and alias it to `value` in the final SELECT.
fn ranked_entries(rows: Vec<tokio_postgres::Row>) -> Vec<RankedEntry> {
    rows.into_iter()
        .map(|row| RankedEntry {
            username: row.get("username"),
            user_id: row.get("user_id"),
            rank: row.get("rank"),
            value: row.get("value"),
            note: None,
        })
        .collect()
}

async fn fetch_today_champions(client: &Client, limit: i64) -> Result<Vec<LeaderboardEntry>> {
    let arms: String = DailyPuzzle::ALL
        .iter()
        .map(|puzzle| {
            format!(
                "SELECT user_id FROM {} WHERE puzzle_date = CURRENT_DATE",
                puzzle.wins_table()
            )
        })
        .collect::<Vec<_>>()
        .join("\nUNION ALL\n");
    let rows = client
        .query(
            &format!(
                "WITH all_today AS (
                    {arms}
                )
                SELECT u.username, a.user_id, COUNT(*)::int AS wins
                FROM all_today a
                JOIN users u ON u.id = a.user_id
                GROUP BY a.user_id, u.username
                ORDER BY wins DESC
                LIMIT $1"
            ),
            &[&limit],
        )
        .await?;

    Ok(rows
        .into_iter()
        .map(|row| LeaderboardEntry {
            username: row.get("username"),
            user_id: row.get("user_id"),
            count: row.get::<_, i32>("wins") as u32,
        })
        .collect())
}

async fn fetch_today_daily_statuses(
    client: &Client,
) -> Result<HashMap<Uuid, DailyCompletionStatus>> {
    let arms: String = DailyPuzzle::ALL
        .iter()
        .map(|puzzle| {
            format!(
                "SELECT DISTINCT user_id, '{key}' AS game, {difficulty} AS difficulty
                 FROM {table}
                 WHERE puzzle_date = CURRENT_DATE",
                key = puzzle.key(),
                difficulty = puzzle.status_difficulty_sql(),
                table = puzzle.wins_table(),
            )
        })
        .collect::<Vec<_>>()
        .join("\nUNION ALL\n");
    let rows = client
        .query(
            &format!("WITH all_today AS ({arms}) SELECT user_id, game, difficulty FROM all_today"),
            &[],
        )
        .await?;

    let mut statuses: HashMap<Uuid, DailyCompletionStatus> = HashMap::new();
    for row in rows {
        let user_id: Uuid = row.get("user_id");
        let game = DailyPuzzle::from_key(row.get("game")).expect("status row game key from roster");
        let difficulty: String = row.get("difficulty");
        statuses
            .entry(user_id)
            .or_default()
            .mark_completed(game, difficulty);
    }

    Ok(statuses)
}
