//! The night city street: static art plus the metadata the runtime needs
//! (collision, landmarks, animation cells). Generated by
//! `scripts/gen_city_map.py --write`; do not hand-edit the literal or the
//! zone constants, tweak the script and re-run.
//!
//! GAME.md, "The night city": the wallet. Shops, the armorer, repairs, the
//! board, the tailor, all on one rainy street with a screen tuned to a
//! dead channel at the end of it. One glyph per person (your runner's
//! mark). Single-width glyphs only. `STYLE` says which register this map
//! is in; `ui.rs` branches on it where the two differ.

#[rustfmt::skip]
pub const MAP_W: u16 = 156;
#[rustfmt::skip]
pub const MAP_H: u16 = 36;

/// Which register the map was generated in.
#[rustfmt::skip]
pub const STYLE: MapStyle = MapStyle::Tiles;

#[rustfmt::skip]
pub const MAP: [&str; MAP_H as usize] = [
    "╔════════════════════════════════════════════════════════════════════╡ ▚ STATIC ROW ▞ ╞════════════════════════════════════════════════════════════════════╗",
    "║                                                                                                                                                          ║",
    "║                                                                                                                                                          ║",
    "║                                                                °   °  .°   °.                                                                            ║",
    "║                                                               ,.  .    ._. ..                                                                            ║",
    "║                  ▒▒.                                          .   ♣     .                                                                                ║",
    "║                  ,.c                               ▒.         . ≈~  c`  ..                                                                               ║",
    "║                   .                                 .         .,  .... .  . ▒                                                                            ║",
    "║                  .°                 #####╬#########.                ..                                                                                   ║",
    "║ #######╬#########  ,                # [.[   . .▪▪.# r               ,≡                                       ▒.                                          ║",
    "║ #.▬. .▬ `  ▬  ▬ #.≡.#####╬######### #######+#######                 ..                                        °            ##╬#######╬##     ▒           ║",
    "║ #.    .. . .  ..# ..# ) ) /. .[.[.# # [.[.[` \".\"` #° ###############   #######╬########                       .            #.. #  .#   #     ,           ║",
    "║ ########+########.  #     ,@      # # `  . @   ` ▌#  #∩∩∩∩∩∩∩∩∩∩∩∩∩#°  #. o.  o.  o  .# ######╬#######╬######≡.            #,▬ #.▬.# ▬ #      °          ║",
    "║ # , .    ` ,.   # ° #.===========.#≡# ===========.#. #  ,   .. .  ,# . #.Y .Y .Y..Y  Y# #   ! !.! @.!.! ! ..#, ########### # @ #   # . #      .          ║",
    "║ #   `      . @  # . #    ,  ,.    #.# . ., ..     #≈~#∩∩∩∩∩∩∩∩∩∩∩∩∩#   #.. .  @   ,`  #.#  ===============  #.°# / \\ x./ # #   #   #.  #      ≡          ║",
    "║ # . .    ,.  . .#.≈~#. ,, . . ..  #`# & ..      &.#  # ,, .  .. .. #   #.============ #≡# ..o  o .o  o  o...#. #  ..@.   #.#.  # , #   #     ≈~          ║",
    "║ #▚#╬####+###╬####.  ##ARMORER##+#╬#.##TAILOR#╬#+###  ##LOCKERS##+#╬# . #. .          .# # ♪          ., .,  #.≈# ======= #r###+##+##+###     ,       ### ║",
    "║  `     .  *. ..`..        . * . . .  .    `.  . ≈~.....* `  .  .    .  #     .  .. .  # #.       ..   ,.    # .#.   ...  #.# ..   ` ., # .°.  ° . °. ░░░ ║",
    "║`>  ,    `. ..   . .. ., ≈~≈~ .., `.       ,,   .``` `.     .  ..≈~≈    ##╬BANDS###+#╬## ##╬DEAD AIR####+##╬## .#╬PATCH#+## #╬#SLEEP##+## $.*.  .≈~ . ░░░ ║",
    "║ ..    ≈~≈,               ~      .  `.. . .≈~≈,.  ..   .....  .... ,   .  ,   ..  `  *.  .. `   ..,.    . . .   .. .     ,   . .  . ,,.,  , .     .` .░░░ ║",
    "║  .  . .` .,  .. ,   , ...  .   @=%=%=.... .      `, .      .=T=T=@,, .`    .   , .     .  ... ≈~≈ , ` . .    .    . ≈~≈~. .  . ...   ,  ` ≈~≈ ..°@° .░░░ ║",
    "║ ####╬#######+#######╬######` .#▞###########+################PAWN#▓## . , . .≈~≈~                    ,.≈~     , ..   .~  ., ..    ≈~≈  .   . .  .===..░░░ ║",
    "║ #,.   , .. ,    ..  . , . # . #. .. ,   .   .., ...  `  ## .,  . . #  ≈~ . ..~ .. .. ?.  .  `  .  ,        .* =)=)=@. .    . .  .   * ...   . .    ..░░░ ║",
    "║ ####+#####+#####+#####+####,°.#,  . . ...  @ . `. .  ▪▪▪## $.) \" [.#. ###╬####+########╬########+####╬###═════╪═══════╪═════>═╪═══════╪═══════╪══════░░░ ║",
    "║ #. . ..#   ..# .  `#,  .  #., #      ` .,. ... ,≡    ▪▪▪##.`. `....#  # .`. ,   .,`. ,  . ... .,  . .  .#        ▪          ∙∙                       ### ║",
    "║ #..  `∩# ..,.#..  ∩#  .  .#   # . .  .▪▪▪`, ..  . .., . ## ======= # r####+#####+#####+#####+#####+######      ·                    ▪                    ║",
    "║ #.▬ `. #.▬   #,▬..,#  ▬. .# ≡ # `     ▪▪▪  .  ` .. ,` ..##. ..  .  #  #   ,, #,    # .   #`.  .#.,. .#..#   ·                                            ║",
    "║ #. .   #.  ..#    .# ,,   #   # ▪▪▪  .` ...   .      . .##..  .,.  #`≡#,  . ∩#   ` #  ..∩#. . .#,. .∩# .#                                                ║",
    "║ #. @`..#. ,..#  .  #   .  # °.# ▪▪▪     ....., ,▪▪▪▪▪ ..## .       #  #. ▬  .# ▬. .#`▬`  #`▬ ,.# ▬,.,#▬ #·                            ·                  ║",
    "║ #.   ..#., . # ,  .# , .  # . # ▪▪▪..  ,., . ` .▪▪▪▪▪   ##   .     #`.#   .  #   . #  ,  #  .  #.    #  #     ▪               ·                          ║",
    "║ ###########################r .######################################▒ # . @  # .. .#   . #  @  # .`..#, #                      ·                         ║",
    "║                             ..                                        #`   . #.   .#  .,,# .  .#.  ..#  #    ·                        ··                 ║",
    "║                            ,▒.                                        ###################################                           ▪                    ║",
    "║                                                                                                                         ·     ·    ·  ·                  ║",
    "║                                                                                                                  ·                                       ║",
    "╚═══════════════════════════════════════════════════════════════════════╡ the wire ╞═══════════════════════════════════════════════════════════════════════╝"
];

/// Cells nothing walks through, one byte per cell, row-major: `#` solid,
/// `.` open.
#[rustfmt::skip]
const SOLID: [&str; MAP_H as usize] = [
    "############################################################################################################################################################",
    "############################################################################################################################################################",
    "############################################################################################################################################################",
    "################################################################...............#############################################################################",
    "################################################################..........#....#############################################################################",
    "#####################.##########################################....#..........#############################################################################",
    "###################..#################################.#########......#........#############################################################################",
    "###################...###############################..#########..............##############################################################################",
    "###################...###############################..###############..####################################################################################",
    "###################...#################.#.#......##.#.################..########################################.###########################################",
    "###.#...#....#..#.#...#######################.#######..###############..#######################################..###############################.###########",
    "###...............#...#.#.#.#...#.#.###.#.#.#..#.#..#..###############..#######################################..#############...#...#...######..###########",
    "##########.########...#......#......#.#......#.....##..###############..##..#...#...#...#######################..#############.#.#.#.#.#.######..###########",
    "###...............#...#.###########.#.#.###########.#..#.............#..##.#..#..#..#..##.#...#.#.#.#.#.#.#...#..#############.#.#...#...######..###########",
    "###............#..#...#.............#.#.............#..###############..##......#.......#.#..###############..#..#.#.#.#.#.###...#...#...######..###########",
    "###...............#...#.............#.#.#.........#.#..#.............#..##.############.#.#...#..#..#..#..#...#..#....#....#.#...#...#...######..###########",
    "##########.########...###########.###.###########.###..###########.###..##..............#.#.#.................#..#.#######.#####.##.##.########..###########",
    "#...........#.................#..........................#...............#..............#.#...................#..#.........#.#...........#.............#####",
    "#........................................................................###########.####.###############.#####..########.##.##########.##.#.#.........#####",
    "#.....................................................................................#................................................................#####",
    "#................................######.......................######..............................................................................###..#####",
    "##############.##############...#############.########################............................................................................###..#####",
    "###.........................#...#.........................##.........#.................#......................#.######................#................#####",
    "######.#####.#####.#####.####...#............#.........#####.#.#.#.#.#..########.#################.###########################.#############################",
    "###......#.....#.....#......#...#......................#####.........#..#.................................##################################################",
    "###.....##.....#....##......#...#.......###...............##.#######.#.#####.#####.#####.#####.#####.#######################################################",
    "###.#....#.#...#.#...#..#...#...#.......###...............##.........#..#......#.....#.....#.....#.....#..##################################################",
    "###......#.....#.....#......#...#.###.....................##.........#..#.....##.....#....##.....#....##..##################################################",
    "###..#...#.....#.....#......#...#.###.............#####...##.........#..#..#...#.#...#.#...#.#...#.#...##.##################################################",
    "###......#.....#.....#......#...#.###.............#####...##.........#..#......#.....#.....#.....#.....#..##################################################",
    "##############################..#######################################.#...#..#.....#.....#..#..#.....#..##################################################",
    "#############################...#########################################......#.....#.....#.....#.....#..##################################################",
    "#############################.#.############################################################################################################################",
    "############################################################################################################################################################",
    "############################################################################################################################################################",
    "############################################################################################################################################################"
];

/// Where your runner appears: on the stairs up from the wire.
#[rustfmt::skip]
pub const SPAWN: (u16, u16) = (126, 23);
/// An open street cell with nothing within reach (for the tests).
#[rustfmt::skip]
pub const OPEN: (u16, u16) = (44, 18);

/// The street sign on the top wall.
#[rustfmt::skip]
pub const TITLE: Zone = Zone { x0: 69, y0: 0, x1: 86, y1: 0 };
/// The far skyline, when the register has one: rain falls across it.
#[rustfmt::skip]
pub const SKY: Option<Zone> = None;
/// The antenna mast's light, when the register has one.
#[rustfmt::skip]
pub const MAST_LIGHT: Option<(u16, u16)> = None;
/// The street band: everything walkable lies in it, plus the stalls.
#[rustfmt::skip]
pub const STREET: Zone = Zone { x0: 1, y0: 17, x1: 150, y1: 22 };
/// The railing over the drop.
#[rustfmt::skip]
pub const RAIL_Y: u16 = 23;
/// The lower city, far below the railing: lights only.
#[rustfmt::skip]
pub const DROP: Zone = Zone { x0: 107, y0: 24, x1: 154, y1: 34 };
/// The screen's face: static, and now and then the test pattern.
#[rustfmt::skip]
pub const SCREEN_FACE: Zone = Zone { x0: 151, y0: 17, x1: 153, y1: 23 };
/// The bits machine's display (drawn) or the machine itself (tiles).
#[rustfmt::skip]
pub const BITS_SCREEN: Zone = Zone { x0: 139, y0: 18, x1: 139, y1: 18 };
/// The board kiosk, and its title row when it has one.
#[rustfmt::skip]
pub const BOARD: Zone = Zone { x0: 87, y0: 22, x1: 87, y1: 22 };
#[rustfmt::skip]
pub const BOARD_SIGN: Option<Zone> = None;
/// The stairs down to the lower city: their signs (drawn) or the tile.
#[rustfmt::skip]
pub const STAIRS_SIGNS: &[Zone] = &[Zone { x0: 2, y0: 18, x1: 2, y1: 18 }];
/// The stairs up to the wire (the way out), and their sign when drawn.
#[rustfmt::skip]
pub const WIRE: Zone = Zone { x0: 125, y0: 23, x1: 127, y1: 23 };
#[rustfmt::skip]
pub const WIRE_SIGN: Option<Zone> = None;
/// The one dead letter on the lockers' sign: always dark.
#[rustfmt::skip]
pub const DEAD_LETTER: (u16, u16) = (61, 16);

/// A neon sign: the letters, and the color they burn.
#[derive(Debug, Clone, Copy)]
pub struct Sign {
    pub zone: Zone,
    pub color: Neon,
}

/// A building: its footprint, and the neon its walls take (`None` for
/// plain concrete). Tiles only; empty when drawn.
#[derive(Debug, Clone, Copy)]
pub struct Building {
    pub zone: Zone,
    pub color: Option<Neon>,
}

/// The shop names in neon.
#[rustfmt::skip]
pub const SIGNS: &[Sign] = &[
    Sign { zone: Zone { x0: 24, y0: 16, x1: 30, y1: 16 }, color: Neon::Red },
    Sign { zone: Zone { x0: 40, y0: 16, x1: 45, y1: 16 }, color: Neon::Magenta },
    Sign { zone: Zone { x0: 57, y0: 16, x1: 63, y1: 16 }, color: Neon::Cyan },
    Sign { zone: Zone { x0: 76, y0: 18, x1: 80, y1: 18 }, color: Neon::Green },
    Sign { zone: Zone { x0: 93, y0: 18, x1: 100, y1: 18 }, color: Neon::Amber },
    Sign { zone: Zone { x0: 115, y0: 18, x1: 119, y1: 18 }, color: Neon::White },
    Sign { zone: Zone { x0: 128, y0: 18, x1: 132, y1: 18 }, color: Neon::Cyan },
    Sign { zone: Zone { x0: 62, y0: 21, x1: 65, y1: 21 }, color: Neon::Red },
];

/// Signs and tags in the city's script (the glyph alphabet).
#[rustfmt::skip]
pub const BANNERS: &[Sign] = &[
    Sign { zone: Zone { x0: 3, y0: 16, x1: 3, y1: 16 }, color: Neon::Magenta },
    Sign { zone: Zone { x0: 33, y0: 21, x1: 33, y1: 21 }, color: Neon::Cyan },
];

/// The carts and stalls: their name row (drawn) or their vendor (tiles).
#[rustfmt::skip]
pub const CART_SIGNS: &[Sign] = &[
    Sign { zone: Zone { x0: 147, y0: 20, x1: 147, y1: 20 }, color: Neon::Magenta },
    Sign { zone: Zone { x0: 33, y0: 20, x1: 33, y1: 20 }, color: Neon::Amber },
    Sign { zone: Zone { x0: 67, y0: 20, x1: 67, y1: 20 }, color: Neon::Cyan },
    Sign { zone: Zone { x0: 117, y0: 22, x1: 117, y1: 22 }, color: Neon::Red },
];

/// The awnings hanging over the sidewalk, one per facade (drawn only).
#[rustfmt::skip]
pub const AWNINGS: &[Zone] = &[

];

/// Where windows flicker: window fields (drawn) or whole buildings (tiles).
#[rustfmt::skip]
pub const WINDOWS: &[Zone] = &[
    Zone { x0: 2, y0: 9, x1: 18, y1: 16 },
    Zone { x0: 22, y0: 10, x1: 36, y1: 16 },
    Zone { x0: 38, y0: 8, x1: 52, y1: 16 },
    Zone { x0: 55, y0: 11, x1: 69, y1: 16 },
    Zone { x0: 73, y0: 11, x1: 88, y1: 18 },
    Zone { x0: 90, y0: 12, x1: 110, y1: 18 },
    Zone { x0: 113, y0: 13, x1: 123, y1: 18 },
    Zone { x0: 125, y0: 10, x1: 137, y1: 18 },
    Zone { x0: 2, y0: 21, x1: 28, y1: 30 },
    Zone { x0: 32, y0: 21, x1: 58, y1: 30 },
    Zone { x0: 59, y0: 21, x1: 69, y1: 30 },
    Zone { x0: 72, y0: 23, x1: 106, y1: 32 },
];

/// The buildings, for wall colors (tiles only).
#[rustfmt::skip]
pub const BUILDINGS: &[Building] = &[
    Building { zone: Zone { x0: 2, y0: 9, x1: 18, y1: 16 }, color: None },
    Building { zone: Zone { x0: 22, y0: 10, x1: 36, y1: 16 }, color: Some(Neon::Red) },
    Building { zone: Zone { x0: 38, y0: 8, x1: 52, y1: 16 }, color: Some(Neon::Magenta) },
    Building { zone: Zone { x0: 55, y0: 11, x1: 69, y1: 16 }, color: Some(Neon::Cyan) },
    Building { zone: Zone { x0: 73, y0: 11, x1: 88, y1: 18 }, color: Some(Neon::Green) },
    Building { zone: Zone { x0: 90, y0: 12, x1: 110, y1: 18 }, color: Some(Neon::Amber) },
    Building { zone: Zone { x0: 113, y0: 13, x1: 123, y1: 18 }, color: Some(Neon::White) },
    Building { zone: Zone { x0: 125, y0: 10, x1: 137, y1: 18 }, color: Some(Neon::Cyan) },
    Building { zone: Zone { x0: 2, y0: 21, x1: 28, y1: 30 }, color: None },
    Building { zone: Zone { x0: 32, y0: 21, x1: 58, y1: 30 }, color: None },
    Building { zone: Zone { x0: 59, y0: 21, x1: 69, y1: 30 }, color: Some(Neon::Red) },
    Building { zone: Zone { x0: 72, y0: 23, x1: 106, y1: 32 }, color: None },
];

/// Steam rises from these cells (vents, grates, the noodle bowls).
#[rustfmt::skip]
pub const VENTS: &[(u16, u16)] = &[(20, 10), (37, 13), (71, 9), (89, 15), (111, 12), (144, 14), (30, 26), (35, 20), (37, 20), (71, 27)];

/// Puddle cells: they catch the neon.
#[rustfmt::skip]
pub const PUDDLES: &[(u16, u16)] = &[(8, 19), (9, 19), (10, 19), (26, 18), (27, 18), (28, 18), (29, 18), (27, 19), (44, 19), (45, 19), (46, 19), (50, 17), (51, 17), (66, 18), (67, 18), (68, 18), (78, 21), (79, 21), (80, 21), (81, 21), (79, 22), (96, 20), (97, 20), (98, 20), (104, 21), (105, 21), (118, 20), (119, 20), (120, 20), (121, 20), (119, 21), (131, 21), (132, 21), (133, 21), (140, 20), (141, 20), (142, 20), (146, 18), (147, 18), (72, 22), (73, 22), (53, 14), (54, 14), (66, 6), (67, 6), (20, 15), (21, 15), (112, 16), (143, 15), (144, 15)];

/// Street lamps: a pool of light around each.
#[rustfmt::skip]
pub const LAMPS: &[(u16, u16)] = &[(12, 17), (30, 17), (57, 17), (86, 19), (110, 22), (134, 22), (141, 18)];

/// The lower city's lights, seen from the railing.
#[rustfmt::skip]
pub const DROP_LIGHTS: &[(u16, u16)] = &[(115, 24), (126, 24), (127, 24), (113, 25), (134, 25), (110, 26), (107, 28), (136, 28), (112, 29), (128, 29), (129, 30), (111, 31), (136, 31), (137, 31), (134, 32), (122, 33), (128, 33), (133, 33), (136, 33), (115, 34)];

/// The two registers the generator knows.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MapStyle {
    /// Front-on facades and carts under a skyline.
    Drawn,
    /// Top-down, one tile per thing.
    Tiles,
}

/// The closed neon palette. Mapped onto the theme in `ui.rs`, never to raw
/// colors, so the city follows whatever palette the person picked.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Neon {
    Cyan,
    Magenta,
    Red,
    Amber,
    Green,
    White,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Zone {
    pub x0: u16,
    pub y0: u16,
    pub x1: u16,
    pub y1: u16,
}

impl Zone {
    pub fn contains(&self, x: u16, y: u16) -> bool {
        x >= self.x0 && x <= self.x1 && y >= self.y0 && y <= self.y1
    }

    /// Chebyshev distance from a point to this rectangle (0 when inside).
    pub fn distance(&self, x: u16, y: u16) -> u16 {
        let dx = self.x0.saturating_sub(x).max(x.saturating_sub(self.x1));
        let dy = self.y0.saturating_sub(y).max(y.saturating_sub(self.y1));
        dx.max(dy)
    }
}

/// Everything on the street you can walk up to, in popover priority order.
/// The shops are the wallet (GAME.md); the rest is the street.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Landmark {
    Armorer,
    Tailor,
    Lockers,
    Bands,
    Bar,
    Screen,
    Repairs,
    Board,
    Bits,
    Noodles,
    Umbrellas,
    Blades,
    Reader,
    Stairs,
    Wire,
}

impl Landmark {
    /// Every landmark, in popover priority order.
    pub const ALL: [Landmark; 15] = [
        Landmark::Armorer,
        Landmark::Tailor,
        Landmark::Lockers,
        Landmark::Bands,
        Landmark::Bar,
        Landmark::Screen,
        Landmark::Repairs,
        Landmark::Board,
        Landmark::Bits,
        Landmark::Noodles,
        Landmark::Umbrellas,
        Landmark::Blades,
        Landmark::Reader,
        Landmark::Stairs,
        Landmark::Wire,
    ];

    /// The cells that put the player within reach: in front of a counter,
    /// around a stall, on the stairs.
    #[rustfmt::skip]
    pub fn reach(self) -> Zone {
        match self {
            Landmark::Armorer => Zone { x0: 24, y0: 14, x1: 34, y1: 14 },
            Landmark::Tailor => Zone { x0: 40, y0: 14, x1: 50, y1: 14 },
            Landmark::Lockers => Zone { x0: 56, y0: 13, x1: 68, y1: 15 },
            Landmark::Bands => Zone { x0: 75, y0: 16, x1: 86, y1: 16 },
            Landmark::Bar => Zone { x0: 93, y0: 15, x1: 107, y1: 16 },
            Landmark::Screen => Zone { x0: 150, y0: 17, x1: 150, y1: 22 },
            Landmark::Repairs => Zone { x0: 115, y0: 17, x1: 121, y1: 17 },
            Landmark::Board => Zone { x0: 87, y0: 22, x1: 87, y1: 22 },
            Landmark::Bits => Zone { x0: 139, y0: 18, x1: 139, y1: 18 },
            Landmark::Noodles => Zone { x0: 33, y0: 20, x1: 38, y1: 20 },
            Landmark::Umbrellas => Zone { x0: 62, y0: 20, x1: 67, y1: 20 },
            Landmark::Blades => Zone { x0: 112, y0: 22, x1: 117, y1: 22 },
            Landmark::Reader => Zone { x0: 146, y0: 20, x1: 148, y1: 21 },
            Landmark::Stairs => Zone { x0: 2, y0: 18, x1: 2, y1: 18 },
            Landmark::Wire => Zone { x0: 126, y0: 23, x1: 126, y1: 23 },
        }
    }

    /// How close the player has to stand.
    #[rustfmt::skip]
    fn reach_distance(self) -> u16 {
        match self {
            Landmark::Armorer => 0,
            Landmark::Tailor => 0,
            Landmark::Lockers => 0,
            Landmark::Bands => 0,
            Landmark::Bar => 0,
            Landmark::Screen => 0,
            Landmark::Repairs => 0,
            Landmark::Board => 1,
            Landmark::Bits => 1,
            Landmark::Noodles => 1,
            Landmark::Umbrellas => 1,
            Landmark::Blades => 1,
            Landmark::Reader => 1,
            Landmark::Stairs => 0,
            Landmark::Wire => 0,
        }
    }
}

/// The landmark the player is close enough to, if any.
pub fn nearest_landmark(x: u16, y: u16) -> Option<Landmark> {
    Landmark::ALL
        .into_iter()
        .find(|landmark| landmark.reach().distance(x, y) <= landmark.reach_distance())
}

/// The street as a padded char grid, decoded once per process.
pub fn grid() -> &'static [Vec<char>] {
    static GRID: std::sync::OnceLock<Vec<Vec<char>>> = std::sync::OnceLock::new();
    GRID.get_or_init(|| {
        MAP.iter()
            .map(|row| {
                let mut cells: Vec<char> = row.chars().collect();
                cells.resize(MAP_W as usize, ' ');
                cells
            })
            .collect()
    })
}

/// The map char at `(x, y)`; rows shorter than `MAP_W` read as open street.
pub fn char_at(x: u16, y: u16) -> char {
    if x >= MAP_W || y >= MAP_H {
        return ' ';
    }
    grid()[y as usize][x as usize]
}

/// Whether a runner can stand on `(x, y)`: the solid bitmap says no for
/// walls, counters, stalls, the railing and the drop.
pub fn walkable(x: u16, y: u16) -> bool {
    if x == 0 || y == 0 || x >= MAP_W - 1 || y >= MAP_H - 1 {
        return false;
    }
    SOLID[y as usize].as_bytes()[x as usize] == b'.'
}

#[cfg(test)]
#[path = "map_test.rs"]
mod map_test;
