//! Database connection pool using tokio-postgres + deadpool.

use anyhow::{Context, Result};

// Embedded migrations - auto-generated by build.rs
include!(concat!(env!("OUT_DIR"), "/migrations.rs"));
use deadpool_postgres::{
    Config, CreatePoolError, ManagerConfig, Pool, PoolConfig, RecyclingMethod, Runtime,
};
use tokio_postgres::NoTls;

/// Database configuration loaded from environment.
#[derive(Debug, Clone)]
pub struct DbConfig {
    pub host: String,
    pub port: u16,
    pub user: String,
    pub password: String,
    pub dbname: String,
    pub max_pool_size: usize,
}

impl Default for DbConfig {
    fn default() -> Self {
        Self {
            host: "localhost".to_string(),
            port: 5432,
            user: "postgres".to_string(),
            password: "postgres".to_string(),
            dbname: "postgres".to_string(),
            max_pool_size: 16,
        }
    }
}

impl DbConfig {
    /// Load configuration from environment variables.
    ///
    /// Environment variables:
    /// - `LATE_DB_HOST` (default: localhost)
    /// - `LATE_DB_PORT` (default: 5432)
    /// - `LATE_DB_USER` (default: postgres)
    /// - `LATE_DB_PASSWORD` (default: postgres)
    /// - `LATE_DB_NAME` (default: postgres)
    /// - `LATE_DB_POOL_SIZE` (default: 16)
    pub fn from_env() -> Self {
        let defaults = Self::default();
        Self {
            host: std::env::var("LATE_DB_HOST").unwrap_or(defaults.host),
            port: std::env::var("LATE_DB_PORT")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or(defaults.port),
            user: std::env::var("LATE_DB_USER").unwrap_or(defaults.user),
            password: std::env::var("LATE_DB_PASSWORD").unwrap_or(defaults.password),
            dbname: std::env::var("LATE_DB_NAME").unwrap_or(defaults.dbname),
            max_pool_size: std::env::var("LATE_DB_POOL_SIZE")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or(defaults.max_pool_size),
        }
    }
}

/// Create a connection pool from configuration.
///
/// Uses `RecyclingMethod::Verified` for reliable connection health checks.
/// This is slightly slower than the default `Fast` method but ensures
/// connections are actually usable, important for unreliable networks.
pub fn create_pool(cfg: &DbConfig) -> Result<Pool, CreatePoolError> {
    let mut pool_cfg = Config::new();
    pool_cfg.host = Some(cfg.host.clone());
    pool_cfg.port = Some(cfg.port);
    pool_cfg.user = Some(cfg.user.clone());
    pool_cfg.password = Some(cfg.password.clone());
    pool_cfg.dbname = Some(cfg.dbname.clone());
    pool_cfg.manager = Some(ManagerConfig {
        recycling_method: RecyclingMethod::Verified,
    });
    let mut pool_config = PoolConfig::new(cfg.max_pool_size);
    pool_config.timeouts.wait = Some(std::time::Duration::from_secs(5));
    pool_cfg.pool = Some(pool_config);

    pool_cfg.create_pool(Some(Runtime::Tokio1), NoTls)
}

/// Wrapper around the connection pool with helper methods.
#[derive(Clone)]
pub struct Db {
    pool: Pool,
    config: DbConfig,
}

impl Db {
    /// Create a new Db instance from configuration.
    pub fn new(cfg: &DbConfig) -> Result<Self> {
        let pool = create_pool(cfg).context("failed to create database pool")?;
        Ok(Self {
            pool,
            config: cfg.clone(),
        })
    }

    /// Create from environment variables.
    pub fn from_env() -> Result<Self> {
        Self::new(&DbConfig::from_env())
    }

    /// Get a connection from the pool.
    ///
    /// Times out after 5 seconds if no connection is available.
    pub async fn get(&self) -> Result<deadpool_postgres::Client> {
        self.pool
            .get()
            .await
            .context("failed to get database connection from pool")
    }

    /// Check if the database is reachable.
    ///
    /// Useful for health checks and startup validation.
    pub async fn health(&self) -> Result<()> {
        let client = self.get().await?;
        client
            .simple_query("SELECT 1")
            .await
            .context("health check query failed")?;
        Ok(())
    }

    /// Get the underlying pool for advanced usage.
    pub fn pool(&self) -> &Pool {
        &self.pool
    }

    /// Get the configuration used to create the pool.
    pub fn config(&self) -> &DbConfig {
        &self.config
    }

    /// Get pool statistics.
    pub fn status(&self) -> deadpool_postgres::Status {
        self.pool.status()
    }

    /// Run pending database migrations.
    ///
    /// Creates a `_migrations` table to track applied migrations.
    /// Each migration runs in its own transaction.
    pub async fn migrate(&self) -> Result<()> {
        let client = self.get().await?;

        // Create migrations tracking table
        client
            .batch_execute(
                "CREATE TABLE IF NOT EXISTS _migrations (
                    name TEXT PRIMARY KEY,
                    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )",
            )
            .await
            .context("failed to create migrations table")?;

        for (name, sql) in MIGRATIONS {
            let row = client
                .query_one(
                    "SELECT COUNT(*)::int FROM _migrations WHERE name = $1",
                    &[name],
                )
                .await
                .context("failed to check migration status")?;

            let count: i32 = row.get(0);
            if count > 0 {
                continue;
            }

            tracing::info!(migration = %name, "applying migration");

            client
                .batch_execute(sql)
                .await
                .with_context(|| format!("failed to apply migration: {name}"))?;

            client
                .execute("INSERT INTO _migrations (name) VALUES ($1)", &[name])
                .await
                .with_context(|| format!("failed to record migration: {name}"))?;

            tracing::info!(migration = %name, "migration applied");
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_config_values() {
        let cfg = DbConfig::default();
        assert_eq!(cfg.host, "localhost");
        assert_eq!(cfg.port, 5432);
        assert_eq!(cfg.user, "postgres");
        assert_eq!(cfg.password, "postgres");
        assert_eq!(cfg.dbname, "postgres");
        assert_eq!(cfg.max_pool_size, 16);
    }

    #[test]
    fn pool_creation_is_lazy() {
        let cfg = DbConfig::default();
        let result = create_pool(&cfg);
        assert!(result.is_ok());
    }

    #[test]
    fn db_new_succeeds_without_connection() {
        let cfg = DbConfig::default();
        let result = Db::new(&cfg);
        assert!(result.is_ok());
    }

    #[test]
    fn db_status_starts_empty() {
        let cfg = DbConfig::default();
        let db = Db::new(&cfg).unwrap();
        let status = db.status();
        assert_eq!(status.size, 0);
        assert_eq!(status.available, 0);
    }
}
