//! Development object storage. Trusted local object URLs resolve directly to
//! disk; user-supplied URLs still go through the public-network SSRF checks.
use std::{path::PathBuf, sync::OnceLock};

use anyhow::{Context, Result, ensure};
use tokio::io::AsyncReadExt;

use crate::config::{Env, FilesConfig};

struct LocalStore {
    directory: PathBuf,
    url_prefix: String,
}

static STORE: OnceLock<LocalStore> = OnceLock::new();

pub fn configure(env: Env, files: Option<&FilesConfig>) -> Result<()> {
    if let Some(files) = files
        && let Some(directory) = &files.local_directory
    {
        ensure!(
            env != Env::Prod,
            "local uploads are only available in development"
        );
        STORE
            .set(LocalStore {
                directory: directory.clone(),
                url_prefix: format!("{}/", files.public_base_url.trim_end_matches('/')),
            })
            .map_err(|_| anyhow::anyhow!("local upload storage already configured"))?;
    }
    Ok(())
}

/// Accept only the object keys generated by image_upload, never filesystem
/// paths, percent escapes, query strings, or arbitrary localhost URLs.
fn valid_key(key: &str) -> bool {
    let parts: Vec<_> = key.split('/').collect();
    match parts.as_slice() {
        ["puzzle-art", name] => name
            .strip_suffix(".png")
            .is_some_and(|hash| hash.len() == 64 && hash.bytes().all(|b| b.is_ascii_hexdigit())),
        ["chat", year, month, name] => {
            year.len() == 4
                && year.bytes().all(|b| b.is_ascii_digit())
                && month.len() == 2
                && month.bytes().all(|b| b.is_ascii_digit())
                && name.rsplit_once('.').is_some_and(|(id, ext)| {
                    uuid::Uuid::parse_str(id).is_ok()
                        && matches!(ext, "png" | "jpg" | "gif" | "webp")
                })
        }
        _ => false,
    }
}

pub(crate) async fn read_url(url: &str, max_bytes: usize) -> Option<Result<Vec<u8>>> {
    let store = STORE.get()?;
    let key = url.strip_prefix(&store.url_prefix)?;
    Some(read_key(&store.directory, key, max_bytes).await)
}

pub(crate) async fn read_key(
    directory: &std::path::Path,
    key: &str,
    max_bytes: usize,
) -> Result<Vec<u8>> {
    ensure!(valid_key(key), "invalid local image key");
    let file = tokio::fs::File::open(directory.join(key))
        .await
        .context("local image not found")?;
    let mut bytes = Vec::new();
    file.take(max_bytes as u64 + 1)
        .read_to_end(&mut bytes)
        .await?;
    ensure!(bytes.len() <= max_bytes, "image is too large");
    Ok(bytes)
}

pub(crate) async fn write(directory: &std::path::Path, key: &str, bytes: &[u8]) -> Result<()> {
    ensure!(valid_key(key), "invalid local image key");
    let path = directory.join(key);
    tokio::fs::create_dir_all(path.parent().context("missing image directory")?).await?;
    // Rename within the same directory so readers never see a partial PNG.
    let temporary = path.with_extension(format!("{}.tmp", uuid::Uuid::now_v7()));
    tokio::fs::write(&temporary, bytes).await?;
    tokio::fs::rename(temporary, path).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::valid_key;

    #[test]
    fn only_generated_object_keys_are_allowed() {
        assert!(valid_key(&format!("puzzle-art/{}.png", "a".repeat(64))));
        assert!(valid_key(
            "chat/2026/09/01994133-6789-7000-8000-123456789abc.png"
        ));
        for key in [
            "../server_key",
            "chat/2026/09/../../server_key",
            "puzzle-art/%2e%2e/server_key",
            "chat/2026/09/invalid.png",
            "chat/2026/09/01994133-6789-7000-8000-123456789abc.png?x=1",
        ] {
            assert!(!valid_key(key), "{key}");
        }
    }
}
